---
name: github-release
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  create-github-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: build
        uses: ./.github/actions/build

      - name: Upload binaries to release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: dist/**
