---
name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build-release-binaries:
    runs-on: ubuntu-22.04
    if: |
      contains(github.event.head_commit.message, '(main): release')
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with: {go_arch: amd64}
      - uses: ./.github/actions/build
        with: {go_arch: arm64}

  release-please:
    runs-on: ubuntu-22.04
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
        id: release
        with:
          release-type: go
          package-name: test-composite-actions

  upload-release-binaries:
    needs: [build-release-binaries, release-please]
    runs-on: ubuntu-22.04
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 #v4.3.0
        with:
          path: dist
          merge-multiple: true
      - name: Upload Release Artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh release upload ${{ needs.release-please.outputs.tag_name }} binary_*
