---
name: test-n-build
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-n-build
  cancel-in-progress: true

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '(main): release')
    runs-on: ubuntu-22.04
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with: {go_arch: amd64}
      - uses: ./.github/actions/build
        with: {go_arch: arm64}
  list-binaries:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: gh run download -p '*,'
      - run: ls -lah
