---
name: test-n-build
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-n-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
